# Generated by Django 3.0.3 on 2020-02-17 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200217_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='categories',
            new_name='name',
        ),
    ]
