# Generated by Django 3.0.3 on 2020-02-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200222_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='static/blog/uploads/%Y/%m/%d/'),
        ),
    ]
