# Generated by Django 3.0.3 on 2020-02-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200223_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
