# Generated by Django 3.0.3 on 2020-02-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_caption_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', height_field='height', upload_to='static/blog/uploads/%Y/%m/%d/', width_field='width'),
        ),
    ]
