# Generated by Django 3.0.3 on 2020-02-23 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200223_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caption_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
