# Generated by Django 3.0.3 on 2020-02-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200223_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='height',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='width',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
