# Generated by Django 3.0.3 on 2020-02-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200223_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='static/blog/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='width',
            field=models.IntegerField(unique=True),
        ),
    ]
