# Generated by Django 3.0.3 on 2020-02-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200223_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
