# Generated by Django 3.0.3 on 2020-02-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200223_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('categoria',)},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoria',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
