# Generated by Django 3.0.3 on 2020-02-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200226_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='published_date',
        ),
    ]
